"use client";

import { ArrowRight, Check, Download, Laptop, MonitorDown, Sparkles, Zap } from "lucide-react";
import Link from "next/link";

const plans = [
    { name: "Free", price: "$0", detail: "For exploring the workspace", items: ["1 basic AI model", "2 hours coding per day", "No custom domains", "Made on Swiss branding"], cta: "Download app" },
    { name: "Builder", price: "$7.99", detail: "For shipping real projects", items: ["Higher AI models", "6 hours runtime per day", "5 custom domains / month", "Up to 3 agents", "Remove Swiss branding"], cta: "Choose Builder", featured: true },
    { name: "Pro", price: "$21.99", detail: "For serious product teams", items: ["Best AI models", "Unlimited build runtime", "Unlimited publishing and domains", "Unlimited agents", "Remove Swiss branding"], cta: "Choose Pro" },
];

export default function Hero() {
    return (
        <main className="min-h-screen bg-[#f5f6f3] text-[#17231e] swiss-grid">
            <header className="mx-auto flex max-w-7xl items-center justify-between border-b border-[#17231e]/10 px-6 py-5">
                <Link href="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#163b2d] p-1"><img src="/logo.svg.png.png" alt="Swiss Dev logo" className="h-full w-full object-contain" /></span><span><b>Swiss Dev</b><small className="ml-2 text-[10px] uppercase tracking-[.2em] text-[#68776f]">Desktop IDE</small></span></Link>
                <div />
            </header>
            <section className="mx-auto grid max-w-7xl gap-14 px-6 pb-24 pt-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
                <div><p className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-[#61776a]"><Sparkles className="h-4 w-4 text-[#9bbd46]" /> The agentic desktop IDE</p><h1 className="max-w-3xl text-6xl font-semibold leading-[.95] tracking-[-.07em] text-[#163b2d] md:text-8xl">A better place to build.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#68776f]">Swiss Dev brings your agents, codebase, preview, and product decisions into one focused desktop workspace.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#download" className="inline-flex items-center gap-2 rounded-lg bg-[#163b2d] px-5 py-3 font-semibold text-white shadow-lg shadow-[#163b2d]/15"><Download className="h-4 w-4" /> Download Swiss Dev</a><a href="#plans" className="inline-flex items-center gap-2 rounded-lg border border-[#163b2d]/20 bg-white/60 px-5 py-3 font-semibold text-[#163b2d]">View plans <ArrowRight className="h-4 w-4" /></a></div></div>
                <div className="rounded-2xl border border-[#163b2d]/15 bg-[#1b211f] p-3 shadow-2xl shadow-[#163b2d]/20"><div className="rounded-xl border border-white/10 bg-[#252d29] p-5"><div className="mb-5 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#b9e55b]" /><span className="text-xs text-gray-400">swiss-dev / workspace</span></div><div className="grid grid-cols-[42px_130px_1fr] gap-2 text-[11px]"><div className="space-y-2 text-gray-500"><Zap className="h-4 w-4 text-[#b9e55b]" /><span className="block">⌘</span><span className="block">◉</span></div><div className="space-y-2 border-r border-white/10 pr-3 text-gray-400"><p className="text-gray-200">EXPLORER</p><p>▾ src</p><p className="pl-3 text-[#b9e55b]">App.jsx</p><p className="pl-3">index.css</p><p>▾ components</p></div><div className="rounded-lg bg-[#151a18] p-4 font-mono leading-6 text-gray-400"><p><i className="text-[#cf8cf4]">export default</i> <span className="text-[#b9e55b]">function</span> Workspace() &#123;</p><p className="pl-4 text-gray-500">// your agent is ready</p><p className="pl-4">return <span className="text-[#85c7e8]">&lt;Product /&gt;</span>;</p><p>&#125;</p></div></div><div className="mt-5 flex items-center justify-between rounded-lg border border-[#b9e55b]/20 bg-[#b9e55b]/5 px-3 py-2 text-xs text-[#dceeb5]"><span>Agent is reviewing your changes</span><span className="h-2 w-2 animate-pulse rounded-full bg-[#b9e55b]" /></div></div></div>
            </section>
            <section id="download" className="border-y border-[#17231e]/10 bg-white/45"><div className="mx-auto grid max-w-7xl gap-8 px-6 py-16 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68776f]">One focused workspace</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.04em] text-[#163b2d]">Made for your desktop.</h2><p className="mt-4 max-w-md leading-7 text-[#68776f]">Install once, sign in, and keep your projects local to the way you work. Windows 10+ and macOS are supported.</p></div><div className="grid gap-3 sm:grid-cols-2"><a href="/api/download/windows" className="group rounded-xl border border-[#163b2d]/15 bg-white p-4 shadow-sm"><img src="/download_buttons/windowsbutton.png" alt="Download Swiss Dev for Windows 10 and above" className="h-auto w-full object-contain" /><span className="mt-3 flex items-center justify-between text-xs font-semibold text-[#496457]"><span className="flex items-center gap-2"><MonitorDown className="h-4 w-4" /> Windows 10+</span><Download className="h-4 w-4 text-[#91a097] group-hover:text-[#163b2d]" /></span><small className="mt-1 block text-[11px] text-[#91a097]">Download installer</small></a><a href="/api/download/mac" className="group rounded-xl border border-[#163b2d]/15 bg-white p-4 shadow-sm"><img src="/download_buttons/mac-button.png" alt="Download Swiss Dev for macOS" className="h-auto w-full object-contain" /><span className="mt-3 flex items-center justify-between text-xs font-semibold text-[#496457]"><span className="flex items-center gap-2"><Laptop className="h-4 w-4" /> macOS</span><Download className="h-4 w-4 text-[#91a097] group-hover:text-[#163b2d]" /></span><small className="mt-1 block text-[11px] text-[#91a097]">Download installer</small></a></div></div></section>
            <section id="plans" className="mx-auto max-w-7xl px-6 py-20"><div className="mb-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68776f]">Simple capacity plans</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.04em] text-[#163b2d]">Choose your runway.</h2></div><div className="grid gap-4 lg:grid-cols-3">{plans.map((plan) => <article key={plan.name} className={`rounded-xl border p-6 ${plan.featured ? "border-[#163b2d] bg-[#163b2d] text-white shadow-xl" : "border-[#163b2d]/15 bg-white/70"}`}><p className={`text-sm font-bold ${plan.featured ? "text-[#d8f36a]" : "text-[#496457]"}`}>{plan.name}</p><p className="mt-5 text-4xl font-semibold tracking-[-.05em]">{plan.price}<small className={`ml-1 text-sm font-normal ${plan.featured ? "text-white/60" : "text-[#91a097]"}`}>/ month</small></p><p className={`mt-2 text-sm ${plan.featured ? "text-white/65" : "text-[#68776f]"}`}>{plan.detail}</p><ul className="my-7 space-y-3">{plan.items.map((item) => <li key={item} className={`flex gap-2 text-sm ${plan.featured ? "text-white/80" : "text-[#496457]"}`}><Check className={`h-4 w-4 shrink-0 ${plan.featured ? "text-[#d8f36a]" : "text-[#67a977]"}`} />{item}</li>)}</ul><a href={plan.name === "Free" ? "#download" : `/billing?plan=${plan.name.toLowerCase()}`} className={`block rounded-lg px-4 py-3 text-center text-sm font-semibold ${plan.featured ? "bg-[#d8f36a] text-[#163b2d]" : "bg-[#163b2d] text-white"}`}>{plan.cta}</a></article>)}</div><p className="mt-5 text-center text-xs text-[#91a097]">Annual billing: Builder $75/year · Pro $199/year</p></section>
            <footer className="border-t border-[#17231e]/10 px-6 py-8 text-center text-xs text-[#68776f]">Swiss Dev · Desktop-first development for people with something to make.</footer>
        </main>
    );
}
